branches: 
  except:
    - /.*travis.*/

install:
  - git clone https://github.com/casadi/testbot.git
  - cinst -y mingw
  - cinst -y mingw-get
  - cinst -y swig
  - cinst -y pip
  - set PATH=%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin;C:\tools\MinGW\bin
  - mingw-get install gcc g++ msys-base
  - pip install numpy
  
build_script:
  - mkdir build
  - cd build
  - cmake "-GMSYS Makefiles" -DWITH_PYTHON=ON ..
  - make
  - make install
  #- cmake "-GVisual Studio 12 Win64" -H. -B_builds
  #- cmake --build _builds --config "Debug"
